[kubernetes]
symbol = "â›µ "
style = "dim green"
disabled = true

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_status]
untracked = "ğŸ¤·"

[time]
use_12hr = false
style = "bold bright-black"
format = "%H:%M"
disabled = false
